apiVersion: v1
kind: Service
metadata:
  name: externalservice
spec:
  type: LoadBalancer
  selector:
    app: sharedpod
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
---
apiVersion: v1
kind: Service
metadata:
  name: internalservice
spec:
  selector:
    app: sharedpod
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
#Reference
# [1] Google Cloud Services, “Services", Google Cloud Services.,
# [Online]. Available: https://cloud.google.com/kubernetes-engine/docs/concepts/service. 
#[Accessed 15 06 2023].